FROM /%%BALENA_MACHINE_NAME%%-node

COPY package.json /package.json
RUN npm install

# This will copy all files in our root to the working  directory in the container
COPY . ./

# Enable systemd init system in container
ENV INITSYSTEM on

# server.js will run when container starts up on the device
# TODO: PM2 here?
CMD ["node", "server.js"]